// APP
export const CHANGE_SCREEN = "CHANGE_SCREEN";

// SKETCHBOOK
export const TILE_CREATE = "TILE_CREATE";
export const TILE_UPDATE = "TILE_UPDATE";
export const TILE_DELETE = "TILE_DELETE";
export const TILE_SAVE_REQUEST = "TILE_SAVE_REQUEST";
export const TILE_SAVE_SUCCESS = "TILE_SAVE_SUCCESS";
export const TILE_SAVE_FAIL = "TILE_SAVE_FAIL";

// PLAYER
export const ADD_GOLD = "ADD_GOLD";
export const REMOVE_GOLD = "REMOVE_GOLD";
export const ADD_SILVER = "ADD_SILVER";
export const REMOVE_SILVER = "REMOVE_SILVER";
export const ADD_COPPER = "ADD_COPPER";
export const REMOVE_COPPER = "REMOVE_COPPER";
export const ADD_WEAPON = "ADD_WEAPON";
export const REMOVE_WEAPON = "REMOVE_WEAPON";
export const ADD_SHIELD = "ADD_SHIELD";
export const REMOVE_SHIELD = "REMOVE_SHIELD";
export const ADD_XP = "ADD_XP";
export const CHANGE_ENTITY = "CHANGE_ENTITY";
export const CHANGE_PLAYER_POSITION = "CHANGE_PLAYER_POSITION";
export const CREATE_LEVEL = "CREATE_LEVEL";
export const MODIFY_HEALTH = "MODIFY_HEALTH";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const PLAYER_BOUGHT_ITEM = "PLAYER_BOUGHT_ITEM";
export const PLAYER_SOLD_ITEM = "PLAYER_SOLD_ITEM";
export const PLAYER_TRADE_SUCCESS = "PLAYER_TRADE_SUCCESS";
export const PLAYER_TRADE_FAIL = "PLAYER_TRADE_FAIL";
export const INTERACT_WITH_NEUTRAL = "INTERACT_WITH_NEUTRAL";
export const TALK_TO_NPC = "TALK_TO_NPC";
export const LOOK_AROUND = "LOOK_AROUND";
export const LEVEL_EXIT = "LEVEL_EXIT";
export const LEVEL_ENTER = "LEVEL_ENTER";
export const PLAYER_SET_USERNAME = "PLAYER_SET_USERNAME";

// USER
export const USER_TWITER_AUTH_REQUEST = "USER_TWITER_AUTH_REQUEST";
export const USER_TWITER_AUTH_SUCCESS = "USER_TWITER_AUTH_SUCCESS";
export const USER_TWITER_AUTH_FAIL = "USER_TWITER_AUTH_FAIL";
export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

// GAME
export const RESTART = "RESTART";
export const TOGGLE_FOG_MODE = "TOGGLE_FOG_MODE";
export const GAME_LOAD_REQUEST = "GAME_LOAD_REQUEST";
export const GAME_LOAD_SUCCESS = "GAME_LOAD_SUCCESS";
export const GAME_LOAD_FAIL = "GAME_LOAD_FAIL";
export const GAME_SAVE_REQUEST = "GAME_SAVE_REQUEST";
export const GAME_SAVE_SUCCESS = "GAME_SAVE_SUCCESS";
export const GAME_SAVE_FAIL = "GAME_SAVE_FAIL";

// DUNGEON
export const RESET_DUNGEON = "RESET_DUNGEON";
export const SET_END_GAME = "SET_END_GAME";
export const UPDATE_DUNGEON = "UPDATE_DUNGEON";
export const SET_DUNGEON_LEVEL = "SET_DUNGEON_LEVEL";

// NPC
export const TOGGLE_NPC_STORE = "TOGGLE_NPC_STORE";
export const SELECT_NPC = "SELECT_NPC";
export const DESELECT_NPC = "DESELECT_NPC";
export const UPDATE_SELECTED_NPC = "UPDATE_SELECTED_NPC";
export const NPC_BOUGHT_ITEM = "NPC_BOUGHT_ITEM";
export const NPC_SOLD_ITEM = "NPC_SOLD_ITEM";
export const NPC_TRADED_ITEM = "NPC_TRADED_ITEM";

// QUEST
export const QUEST_NEW = "QUEST_NEW";
export const QUEST_PROGRESS = "QUEST_PROGRESS";
export const QUEST_COMPLETE = "QUEST_COMPLETE";
export const QUEST_RESTART = "QUEST_RESTART";
export const QUEST_SKIP = "QUEST_SKIP";
export const QUEST_START = "QUEST_START";
export const QUEST_ABANDON = "QUEST_ABANDON";

// CHAPTER
export const CHAPTER_START = "CHAPTER_START";
export const CHAPTER_PROGRESS = "CHAPTER_PROGRESS";
export const CHAPTER_COMPLETE = "CHAPTER_COMPLETE";

// BOOK
export const BOOK_START = "BOOK_START";
export const BOOK_PROGRESS = "BOOK_PROGRESS";
export const BOOK_COMPLETE = "BOOK_COMPLETE";

// UI
export const UI_TOOLTIPS_TOGGLE_CLICKED = "UI_TOOLTIPS_TOGGLE_CLICKED";
export const UI_UNKNOWN_TOGGLE_CLICKED = "UI_UNKNOWN_TOGGLE_CLICKED";
export const UI_PAPERDOLL_TOGGLE_CLICKED = "UI_PAPERDOLL_TOGGLE_CLICKED";
export const UI_SCOREBOARD_TOGGLE_CLICKED = "UI_SCOREBOARD_TOGGLE_CLICKED";
export const UI_LOG_TOGGLE_CLICKED = "UI_LOG_TOGGLE_CLICKED";
export const UI_SETTINGS_TOGGLE_CLICKED = "UI_SETTINGS_TOGGLE_CLICKED";
export const UI_BACKPACK_TOGGLE_CLICKED = "UI_BACKPACK_TOGGLE_CLICKED";
export const UI_RENDER_QUESTS_ADD = "UI_RENDER_QUESTS_ADD";
export const UI_RENDER_QUESTS_REMOVE = "UI_RENDER_QUESTS_REMOVE";
export const UI_RENDER_SKIN_ADD = "UI_RENDER_SKIN_ADD";
export const UI_RENDER_SKIN_REMOVE = "UI_RENDER_SKIN_REMOVE";
export const UI_RENDER_SKINS_UPDATE_COMPLETE =
  "UI_RENDER_SKINS_UPDATE_COMPLETE";
// UI / SETTINGS / VISIBLE
export const TOGGLE_VISIBLE_SETTINGS = "TOGGLE_VISIBLE_SETTINGS";

// UI / SETTINGS / SAVE
export const UI_SAVE_LOCAL_SETTINGS_REQUEST = "UI_SAVE_LOCAL_SETTINGS_REQUEST";
export const UI_SAVE_LOCAL_SETTINGS_SUCCESS = "UI_SAVE_LOCAL_SETTINGS_SUCCESS";
export const UI_SAVE_LOCAL_SETTINGS_FAIL = "UI_SAVE_LOCAL_SETTINGS_FAIL";
export const UI_SAVE_REMOTE_SETTINGS_REQUEST =
  "UI_SAVE_REMOTE_SETTINGS_REQUEST";
export const UI_SAVE_REMOTE_SETTINGS_SUCCESS =
  "UI_SAVE_REMOTE_SETTINGS_SUCCESS";
export const UI_SAVE_REMOTE_SETTINGS_FAIL = "UI_SAVE_REMOTE_SETTINGS_FAIL";
// UI / SETTINGS / LOAD
export const UI_LOAD_LOCAL_SETTINGS_REQUEST = "UI_LOAD_LOCAL_SETTINGS_REQUEST";
export const UI_LOAD_LOCAL_SETTINGS_SUCCESS = "UI_LOAD_LOCAL_SETTINGS_SUCCESS";
export const UI_LOAD_LOCAL_SETTINGS_FAIL = "UI_LOAD_LOCAL_SETTINGS_FAIL";
export const UI_LOAD_REMOTE_SETTINGS_REQUEST =
  "UI_LOAD_REMOTE_SETTINGS_REQUEST";
export const UI_LOAD_REMOTE_SETTINGS_SUCCESS =
  "UI_LOAD_REMOTE_SETTINGS_SUCCESS";
export const UI_LOAD_REMOTE_SETTINGS_FAIL = "UI_LOAD_REMOTE_SETTINGS_FAIL";

export const UI_PAPERDOLL_VISIBLE_SET = "UI_PAPERDOLL_VISIBLE_SET";
export const UI_BACKPACK_VISIBLE_SET = "UI_BACKPACK_VISIBLE_SET";
export const UI_SCOREBOARD_VISIBLE_SET = "UI_SCOREBOARD_VISIBLE_SET";
export const UI_TOOLTIPS_VISIBLE_SET = "UI_TOOLTIPS_VISIBLE_SET";
export const UI_SETTINGS_VISIBLE_SET = "UI_SETTINGS_VISIBLE_SET";
export const UI_LOG_VISIBLE_SET = "UI_LOG_VISIBLE_SET";
export const UI_ALL_VISIBLE_SET = "UI_ALL_VISIBLE_SET";

// UI SETTINGS
export const SETTING_CHANGE = "SETTING_CHANGE";

// AUTH
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// MISC
export const DISMISS_PIN = "DISMISS_PIN";
