const emails = [
  {
    body: "https://visualgo.net/en\r\n",
    date: "Fri, 13 Sep 2024 06:31:57 -0400",
    email_id: ["191eaf0b32470066"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject:
      "visualising data structures and algorithms through animation - VisuAlgo",
    to: "brandonflowers@gmail.com",
  },
  {
    body: '<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=3D=\r\nutf-8"></head><body dir=3D"auto"><div dir=3D"ltr"><a href=3D"https://x.com/s=\r\nandromaglione/status/1827406099621757407?s=3D43&amp;t=3DJosrImXLm25J_T3QQadm=\r\nMw"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border:=\r\n1px solid #ccd6dd; border-radius: 12px;" width=3D"500" bgcolor=3D"#ffffff"><=\r\ntbody><tr><td colspan=3D"3" style=3D"font-size: 0px; line-height: 0px;" heig=\r\nht=3D"12">&nbsp;</td></tr><tr><td width=3D"18" style=3D"font-size: 0px; line=\r\n-height: 0px; min-width: 18px;">&nbsp;</td><td><table cellpadding=3D"0" cell=\r\nspacing=3D"0" border=3D"0" width=3D"464" align=3D"left"><tbody><tr valign=3D=\r\n"top"><td width=3D"48" valign=3D"top"><a href=3D"https://x.com/sandromaglion=\r\ne?s=3D43"><img src=3D"https://pbs.twimg.com/profile_images/18059713499506769=\r\n92/CIWSZiKB_normal.jpg" style=3D"border-radius: 50%; padding: 0px;" height=3D=\r\n"48" width=3D"48" data-unique-identifier=3D""></a></td><td width=3D"8" style=\r\n=3D"font-size: 0px; line-height: 0px; min-width:8px;"><img src=3D"https://ea=\r\n.twimg.com/email/self_serve/media/spacer.png" width=3D"8" data-unique-identi=\r\nfier=3D""></td><td valign=3D"middle" width=3D"388" style=3D"min-width: 388px=\r\n;"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" align=3D"left" wi=\r\ndth=3D"388"><tbody><tr><td align=3D"left" width=3D"388"><b><a href=3D"https:=\r\n//x.com/sandromaglione?s=3D43" style=3D"font-family: Helvetica, Arial, san-s=\r\nerif; font-size: 14px; line-height: 18px; color: #292c2f; text-decoration: n=\r\none;">Sandro Maglione</a></b></td></tr><tr><td align=3D"left"><a href=3D"htt=\r\nps://x.com/sandromaglione?s=3D43" style=3D"font-family: Helvetica, Arial, sa=\r\nn-serif; font-size: 14px; line-height: 18px; text-decoration: none; color: #=\r\n7e8c98;">=E2=81=A6=E2=80=AA@SandroMaglione=E2=80=AC=E2=81=A9</a></td></tr></=\r\ntbody></table></td><td valign=3D"top" width=3D"20"><img src=3D"https://ea.tw=\r\nimg.com/email/self_serve/media/logo_twitter-1497383721365.png" height=3D"20"=\r\n width=3D"24" data-unique-identifier=3D""></td></tr><tr><td height=3D"9" col=\r\nspan=3D"4" style=3D"font-size: 0px; line-height:0px;"><img src=3D"https://ea=\r\n.twimg.com/self_serve/media/spacer_464x1-1582829598167.png" width=3D"464" he=\r\night=3D"1" data-unique-identifier=3D""></td></tr><tr><td colspan=3D"4" style=\r\n=3D"font-family: Helvetica, Arial, san-serif;color: #292c2f; font-size: 18px=\r\n; line-height: 24px; text-decoration: none;">I am exploring differences betw=\r\neen useState, useReducer (Redux), and actors<br><br>Not all actors need to b=\r\ne state machines =F0=9F=92=A1<br><br>All the details in my upcoming (free) c=\r\nourse =F0=9F=91=87<br><br><a href=3D"https://t.co/0xD2F2uN3V"><span>typeonce=\r\n.dev/course/xstate-=E2=80=A6</span></a></td></tr><tr><td height=3D"3" colspa=\r\nn=3D"4" style=3D"font-size: 0px; line-height:0px;">&nbsp;</td></tr><tr><td c=\r\nolspan=3D"4"><a href=3D"https://x.com/sandromaglione/status/1827406099621757=\r\n407?s=3D43&amp;t=3DJosrImXLm25J_T3QQadmMw" style=3D"font-family: Helvetica, A=\r\nrial, san-serif;color: #667785; font-size: 14px; line-height: 18px; text-dec=\r\noration:none;">2024-08-24, 2:02=E2=80=AFPM</a></td></tr></tbody></table></td=\r\n><td width=3D"18" style=3D"font-size: 0px; line-height: 0px; min-width: 18px=\r\n;">&nbsp;</td></tr><tr><td colspan=3D"3" style=3D"font-size: 0px; line-heigh=\r\nt: 0px;" height=3D"12">&nbsp;</td></tr></tbody></table></a><br></div><div di=\r\nr=3D"ltr"></div></body></html>=\r\n',
    date: "Sat, 24 Aug 2024 14:37:40 -0400",
    email_id: ["19185ae0c1eca1f9"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Post by Sandro Maglione on X",
    to: "brandonflowers@gmail.com",
  },
  {
    body: '<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=3D=\r\nutf-8"></head><body dir=3D"auto"><div dir=3D"ltr"><a href=3D"https://x.com/g=\r\namesparable/status/1813190344672223439?s=3D43&amp;t=3DJosrImXLm25J_T3QQadmMw=\r\n"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border:1p=\r\nx solid #ccd6dd; border-radius: 12px;" width=3D"500" bgcolor=3D"#ffffff"><tb=\r\nody><tr><td colspan=3D"3" style=3D"font-size: 0px; line-height: 0px;" height=\r\n=3D"12">&nbsp;</td></tr><tr><td width=3D"18" style=3D"font-size: 0px; line-h=\r\neight: 0px; min-width: 18px;">&nbsp;</td><td><table cellpadding=3D"0" cellsp=\r\nacing=3D"0" border=3D"0" width=3D"464" align=3D"left"><tbody><tr valign=3D"t=\r\nop"><td width=3D"48" valign=3D"top"><a href=3D"https://x.com/gamesparable?s=3D=\r\n43"><img src=3D"https://pbs.twimg.com/profile_images/1685895549755813888/6Qf=\r\nfQpgw_normal.jpg" style=3D"border-radius: 50%; padding: 0px;" height=3D"48" w=\r\nidth=3D"48" data-unique-identifier=3D""></a></td><td width=3D"8" style=3D"fo=\r\nnt-size: 0px; line-height: 0px; min-width:8px;"><img src=3D"https://ea.twimg=\r\n.com/email/self_serve/media/spacer.png" width=3D"8" data-unique-identifier=3D=\r\n""></td><td valign=3D"middle" width=3D"388" style=3D"min-width: 388px;"><tab=\r\nle cellpadding=3D"0" cellspacing=3D"0" border=3D"0" align=3D"left" width=3D"=\r\n388"><tbody><tr><td align=3D"left" width=3D"388"><b><a href=3D"https://x.com=\r\n/gamesparable?s=3D43" style=3D"font-family: Helvetica, Arial, san-serif; fon=\r\nt-size: 14px; line-height: 18px; color: #292c2f; text-decoration: none;">Par=\r\nable Games - ION Heart Live Now on @Backerkit</a></b></td></tr><tr><td align=\r\n=3D"left"><a href=3D"https://x.com/gamesparable?s=3D43" style=3D"font-family=\r\n: Helvetica, Arial, san-serif; font-size: 14px; line-height: 18px; text-deco=\r\nration: none; color: #7e8c98;">=E2=81=A6=E2=80=AA@GamesParable=E2=80=AC=E2=81=\r\n=A9</a></td></tr></tbody></table></td><td valign=3D"top" width=3D"20"><img s=\r\nrc=3D"https://ea.twimg.com/email/self_serve/media/logo_twitter-1497383721365=\r\n.png" height=3D"20" width=3D"24" data-unique-identifier=3D""></td></tr><tr><=\r\ntd height=3D"9" colspan=3D"4" style=3D"font-size: 0px; line-height:0px;"><im=\r\ng src=3D"https://ea.twimg.com/self_serve/media/spacer_464x1-1582829598167.pn=\r\ng" width=3D"464" height=3D"1" data-unique-identifier=3D""></td></tr><tr><td c=\r\nolspan=3D"4" style=3D"font-family: Helvetica, Arial, san-serif;color: #292c2=\r\nf; font-size: 18px; line-height: 24px; text-decoration: none;">ION Heart. Ex=\r\nplore a post-war galaxy with your mech best friend. =F0=9F=9A=80 Discover ne=\r\nw planets, communities and cultures in this lo-fi solo mech <a href=3D"https=\r\n://x.com/search?q=3D%23TTRPG&amp;src=3Dhash">#TTRPG</a>. =F0=9F=A4=96</td></=\r\ntr><tr><td height=3D"3" colspan=3D"4" style=3D"font-size: 0px; line-height:0=\r\npx;">&nbsp;</td></tr><tr><td colspan=3D"4"><a href=3D"https://x.com/gamespar=\r\nable/status/1813190344672223439?s=3D43&amp;t=3DJosrImXLm25J_T3QQadmMw" style=\r\n=3D"font-family: Helvetica, Arial, san-serif;color: #667785; font-size: 14px=\r\n; line-height: 18px; text-decoration:none;">2024-07-16, 8:34=E2=80=AFAM</a><=\r\n/td></tr></tbody></table></td><td width=3D"18" style=3D"font-size: 0px; line=\r\n-height: 0px; min-width: 18px;">&nbsp;</td></tr><tr><td colspan=3D"3" style=3D=\r\n"font-size: 0px; line-height: 0px;" height=3D"12">&nbsp;</td></tr></tbody></=\r\ntable></a><br></div><div dir=3D"ltr"></div></body></html>=\r\n',
    date: "Sun, 11 Aug 2024 11:34:01 -0400",
    email_id: ["19142134569fe5ed"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Post by Parable Games - ION Heart Live Now on @Backerkit on X",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "https://craftyramen.com/ \r\n\r\nMomofuko or scout \r\n",
    date: "Wed, 7 Aug 2024 16:42:26 -0400",
    email_id: ["1912e9451f6d3a65"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Crafty Ramen",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "\r\nhttps://kotaku.com/elden-ring-shadow-erdtree-how-to-beat-gaius-boss-18516077=\r\n84\r\n",
    date: "Wed, 31 Jul 2024 17:40:07 -0400",
    email_id: ["1910abc75ea156f0"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "How To Defeat Commander Gaius In Shadow Of The Erdtree",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "\r\nhttps://mysqlexplain.com/\r\n",
    date: "Tue, 16 Jul 2024 12:12:45 +0200",
    email_id: ["190bb07c78c8cf2a"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "MySQL Visual Explain",
    to: "brandonflowers@gmail.com",
  },
  {
    body: '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body dir="auto"><div dir="ltr"><br><br><b>James Steidle: Tree planters are misinformed about the impact of what they are doing</b><br><a href="https://flip.it/n5k6tY">https://www.princegeorgecitizen.com/opinion/james-steidle-tree-planters-are-misinformed-about-the-impact-of-what-they-are-doing-9210676</a><br><br>View the article + more on Flipboard.<br><a href="https://flip.it/zda5F3">https://flip.it/zda5F3</a><br><br>Find your favorite topics on Flipboard. Download here.<br><a href="http://flip.it/now">http://flip.it/now</a></div><div dir="ltr"></div></body></html>',
    date: "Fri, 12 Jul 2024 19:23:57 +0200",
    email_id: ["190a7f91b6155b52"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject:
      "James Steidle: Tree planters are misinformed about the impact of what they are doing",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "https://mouseholepress.itch.io/orbital\r\n",
    date: "Fri, 12 Jul 2024 12:24:20 +0200",
    email_id: ["190a678ff46351f6"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Orbital by Jack Harrison",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "https://www.google.com/search?q=3Dsong+emergency+emergency+calling+dr.bleep&=\r\nsca_esv=3D681d2c6e37d88c1e&rlz=3D1CDGOYI_enCA817CA817&hl=3Den-US&sxsrf=3DADL=\r\nYWIJ0S0Te3AydgRBaocQ3JWlmqSxfjA%3A1719693097914&ei=3DKW-AZvq4N7e3wN4PhvuB4As=\r\n&oq=3Dsong+emergency+emergency+calling+dr.bleep&gs_lp=3DEhNtb2JpbGUtZ3dzLXdp=\r\nei1zZXJwIilzb25nIGVtZXJnZW5jeSBlbWVyZ2VuY3kgY2FsbGluZyBkci5ibGVlcDIIEAAYgAQY=\r\nogQyCBAAGIAEGKIEMggQABiABBiiBDIIEAAYogQYiQVIniNQ1hRY3R9wAHgAkAEBmAHvAaABkgmq=\r\nAQUwLjUuMrgBA8gBAPgBAZgCBqACpQjCAgsQABiABBiwAxiiBMICCxAAGLADGKIEGIkFwgIHECMY=\r\nsAIYJ8ICChAhGKABGMMEGAqYAwCIBgGQBgWSBwUwLjQuMqAH4Rs&sclient=3Dmobile-gws-wiz=\r\n-serp#fpstate=3Dive&vld=3Dcid:9b7d476e,vid:gjGG6Y4zPi8,st:0\r\n",
    date: "Sat, 29 Jun 2024 16:32:59 -0400",
    email_id: ["19065b388682d026"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject:
      "https://www.google.com/search?q=song+emergency+emergency+calling+dr.bleep&sca_esv=681d2c6e37d88c1e&rlz=1CDGOYI_enCA817CA817&hl=en-US&sxsrf=ADLYWIJ0S0Te3AydgRBaocQ3JWlmqSxfjA%3A1719693097914&ei=KW-AZvq4N7e3wN4PhvuB4As&oq=song+emergency+emergency+calling+dr.bleep&gs_lp=EhNtb2JpbGUtZ3dzLXdpei1zZXJwIilzb25nIGVtZXJnZW5jeSBlbWVyZ2VuY3kgY2FsbGluZyBkci5ibGVlcDIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBDIIEAAYogQYiQVIniNQ1hRY3R9wAHgAkAEBmAHvAaABkgmqAQUwLjUuMrgBA8gBAPgBAZgCBqACpQjCAgsQABiABBiwAxiiBMICCxAAGLADGKIEGIkFwgIHECMYsAIYJ8ICChAhGKABGMMEGAqYAwCIBgGQBgWSBwUwLjQuMqAH4Rs&sclient=mobile-gws-wiz-serp#fpstate=ive&vld=cid:9b7d476e,vid:gjGG6Y4zPi8,st:0",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "https://pca.st/episode/c3ba865e-9233-47c3-9007-c9bf650b5a43\r\n",
    date: "Tue, 18 Jun 2024 14:31:21 -0400",
    email_id: ["1902c9e308f09ade"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Listicle",
    to: "brandonflowers@gmail.com",
  },
  {
    body: '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body dir="auto"><div dir="ltr"><br><br><b>This Is What a 97-Square-Foot Apartment In Paris Looks Like</b><br><a href="https://flip.it/Q3HhGr">https://www.cubbyathome.com/97-square-foot-paris-apartment-80038204</a><br><br>View the article + more on Flipboard.<br><a href="https://flip.it/LPiOEw">https://flip.it/LPiOEw</a><br><br>Find your favorite topics on Flipboard. Download here.<br><a href="http://flip.it/now">http://flip.it/now</a></div><div dir="ltr"></div></body></html>',
    date: "Mon, 17 Jun 2024 18:50:52 -0400",
    email_id: ["190286574559bdf0"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "This Is What a 97-Square-Foot Apartment In Paris Looks Like",
    to: "brandonflowers@gmail.com",
  },
  {
    body: '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body dir="auto"><div dir="ltr"><br><br><b>Scientists found a power source with negative carbon emissions</b><br><a href="https://flip.it/ftVDLn">https://bgr.com/science/scientists-found-a-power-source-with-negative-carbon-emissions/</a><br><br>View the article + more on Flipboard.<br><a href="https://flip.it/RayjMI">https://flip.it/RayjMI</a><br><br>Find your favorite topics on Flipboard. Download here.<br><a href="http://flip.it/now">http://flip.it/now</a></div><div dir="ltr"></div></body></html>',
    date: "Mon, 17 Jun 2024 18:48:45 -0400",
    email_id: ["1902863970d2f501"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Scientists found a power source with negative carbon emissions",
    to: "brandonflowers@gmail.com",
  },

  {
    body: '<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=3D=\r\nutf-8"></head><body dir=3D"auto"><div dir=3D"ltr"><a href=3D"https://x.com/s=\r\nteventey/status/1797677045964743151?s=3D43&amp;t=3DJosrImXLm25J_T3QQadmMw"><=\r\ntable cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border:1px s=\r\nolid #ccd6dd; border-radius: 12px;" width=3D"500" bgcolor=3D"#ffffff"><tbody=\r\n><tr><td colspan=3D"3" style=3D"font-size: 0px; line-height: 0px;" height=3D=\r\n"12">&nbsp;</td></tr><tr><td width=3D"18" style=3D"font-size: 0px; line-heig=\r\nht: 0px; min-width: 18px;">&nbsp;</td><td><table cellpadding=3D"0" cellspaci=\r\nng=3D"0" border=3D"0" width=3D"464" align=3D"left"><tbody><tr valign=3D"top"=\r\n><td width=3D"48" valign=3D"top"><a href=3D"https://x.com/steventey?s=3D43">=\r\n<img src=3D"https://pbs.twimg.com/profile_images/1506792347840888834/dS-r50J=\r\ne_normal.jpg" style=3D"border-radius: 50%; padding: 0px;" height=3D"48" widt=\r\nh=3D"48" data-unique-identifier=3D""></a></td><td width=3D"8" style=3D"font-=\r\nsize: 0px; line-height: 0px; min-width:8px;"><img src=3D"https://ea.twimg.co=\r\nm/email/self_serve/media/spacer.png" width=3D"8" data-unique-identifier=3D""=\r\n></td><td valign=3D"middle" width=3D"388" style=3D"min-width: 388px;"><table=\r\n cellpadding=3D"0" cellspacing=3D"0" border=3D"0" align=3D"left" width=3D"38=\r\n8"><tbody><tr><td align=3D"left" width=3D"388"><b><a href=3D"https://x.com/s=\r\nteventey?s=3D43" style=3D"font-family: Helvetica, Arial, san-serif; font-siz=\r\ne: 14px; line-height: 18px; color: #292c2f; text-decoration: none;">Steven T=\r\ney</a></b></td></tr><tr><td align=3D"left"><a href=3D"https://x.com/stevente=\r\ny?s=3D43" style=3D"font-family: Helvetica, Arial, san-serif; font-size: 14px=\r\n; line-height: 18px; text-decoration: none; color: #7e8c98;">=E2=81=A6=E2=80=\r\n=AA@steventey=E2=80=AC=E2=81=A9</a></td></tr></tbody></table></td><td valign=\r\n=3D"top" width=3D"20"><img src=3D"https://ea.twimg.com/email/self_serve/medi=\r\na/logo_twitter-1497383721365.png" height=3D"20" width=3D"24" data-unique-ide=\r\nntifier=3D""></td></tr><tr><td height=3D"9" colspan=3D"4" style=3D"font-size=\r\n: 0px; line-height:0px;"><img src=3D"https://ea.twimg.com/self_serve/media/s=\r\npacer_464x1-1582829598167.png" width=3D"464" height=3D"1" data-unique-identi=\r\nfier=3D""></td></tr><tr><td colspan=3D"4" style=3D"font-family: Helvetica, A=\r\nrial, san-serif;color: #292c2f; font-size: 18px; line-height: 24px; text-dec=\r\noration: none;">`streamObject` in the <a href=3D"https://x.com/vercel">=E2=81=\r\n=A6=E2=80=AA@vercel=E2=80=AC=E2=81=A9</a> AI SDK is such a powerful primitiv=\r\ne for building AI UX.<br><br>It makes streaming structured objects (via <a h=\r\nref=3D"https://x.com/zodtypes">=E2=81=A6=E2=80=AA@zodtypes=E2=80=AC=E2=81=A9=\r\n</a>) to the client unbelievably simple.<br><br>=E2=97=86 Example =E2=86=92 <=\r\na href=3D"https://t.co/Innj9z0DQH"><span>git.new/SU5snVq</span></a><br>=E2=97=\r\n=86 Docs =E2=86=92 <a href=3D"https://t.co/ePEzHNHsr2"><span>d.to/streamObje=\r\nct</span></a><br><br><a href=3D"https://t.co/VEO4qfYmeK"><span>x.com/stevent=\r\ney/stat=E2=80=A6</span></a> <a href=3D"https://t.co/KS0LVc189f"><span>pic.tw=\r\nitter.com/KS0LVc189f</span></a></td></tr><tr><td height=3D"3" colspan=3D"4" s=\r\ntyle=3D"font-size: 0px; line-height:0px;">&nbsp;</td></tr><tr><td colspan=3D=\r\n"4"><a href=3D"https://x.com/steventey/status/1797677045964743151?s=3D43&amp=\r\n;t=3DJosrImXLm25J_T3QQadmMw" style=3D"font-family: Helvetica, Arial, san-ser=\r\nif;color: #667785; font-size: 14px; line-height: 18px; text-decoration:none;=\r\n">2024-06-03, 1:09=E2=80=AFPM</a></td></tr></tbody></table></td><td width=3D=\r\n"18" style=3D"font-size: 0px; line-height: 0px; min-width: 18px;">&nbsp;</td=\r\n></tr><tr><td colspan=3D"3" style=3D"font-size: 0px; line-height: 0px;" heig=\r\nht=3D"12">&nbsp;</td></tr></tbody></table></a><br></div><div dir=3D"ltr"></d=\r\niv></body></html>=\r\n',
    date: "Tue, 4 Jun 2024 08:09:50 -0400",
    email_id: ["18fe32801e12a4c1"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Post by Steven Tey on X",
    to: "brandonflowers@gmail.com",
  },

  {
    body: "\r\nhttps://kotaku.com/animal-well-review-metroidvania-puzzle-2024-goty-18514657=\r\n30\r\n",
    date: "Tue, 28 May 2024 16:45:17 -0400",
    email_id: ["18fc0f369bf2f063"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject:
      "=?utf-8?Q?Animal_Well_Review:_2024=E2=80=99s_Newest_GOTY_Contend?=\r\n =?utf-8?Q?er_Has_Arrived?=",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "\r\nhttps://www.val.town/\r\n",
    date: "Sun, 26 May 2024 18:32:30 -0400",
    email_id: ["18fb708b28a8a189"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Val Town",
    to: "brandonflowers@gmail.com",
  },

  {
    body: '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body dir="auto"><div dir="ltr"><br><br><b>Reintroduction of 170 European Bison Could Help Remove CO2 Equivalent of 43,000 Cars, Study Finds</b><br><a href="https://flip.it/YYCHJb">https://www.ecowatch.com/bison-reintroduction-carbon-sequestration-climate-science.html</a><br><br>View the article + more on Flipboard.<br><a href="https://flip.it/x0cuth">https://flip.it/x0cuth</a><br><br>Find your favorite topics on Flipboard. Download here.<br><a href="http://flip.it/now">http://flip.it/now</a></div><div dir="ltr"></div></body></html>',
    date: "Tue, 21 May 2024 18:57:28 -0400",
    email_id: ["18f9d5fee481c022"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject:
      "Reintroduction of 170 European Bison Could Help Remove CO2 Equivalent of 43,000 Cars, Study Finds",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "\r\nhttps://www.behance.net/gallery/196059457/Green-Growth-Futura\r\n",
    date: "Thu, 16 May 2024 15:38:41 -0400",
    email_id: ["18f82ea1c58c98c4"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject: "Green Growth Futura :: Behance",
    to: "brandonflowers@gmail.com",
  },
  {
    body: "https://medium.com/understanding-games/the-magic-circle-febdba265c22\r\n",
    date: "Sat, 11 May 2024 13:54:35 -0400",
    email_id: ["18f68cadc73c7d91"],
    from: "Brandon Flowers <brandonflowers@gmail.com>",
    subject:
      "=?utf-8?Q?The_Magic_Circle._Understanding_Games:_How_Video?=\r\n =?utf-8?Q?=E2=80=A6?=",
    to: "brandonflowers@gmail.com",
  },
];
