const dungeonTypes = [
  { id: 0,
    name: "Bellwoods",
    exits: 1,
    exitsComplete: 0,
    questsComplete: 0,
    type: 'dungeon',
  },
  { id: 1,
    name: "Bellwoods",
    exits: 2,
    exitsComplete: 0,
    questsComplete: 0,
    type: 'dungeon',
  },
  { id: 2,
    name: "Bellwoods",
    exits: 5,
    exitsComplete: 0,
    questsComplete: 0,
    type: 'dungeon',
  },
  { id: 3,
    name: "Bellwoods",
    exits: 5,
    exitsComplete: 0,
    questsComplete: 0,
    type: 'dungeon',
  },
  { id: 4,
    name: "Bellwoods",
    exits: 5,
    exitsComplete: 0,
    questsComplete: 0,
    type: 'dungeon',
  },
]

export default dungeonTypes;
