export const SketchModel = {
  positions: [],
  curMouseX: 0,
  curMouseY: 0,
  bUseSVG: true,
  toolPolygonPoints: [],
  bLogSketch: true,
  overlapThreshold: '99%',
  paperChecker: null,
  selectedWidth: 0,
  selectedHeight: 0,
  selectedColorRGB: 0,
  paper: null,
  parts: null,
  polygonSVGPoints: null,
  curPolyStr: '',
  bTriangleShape: true,
  error: {},
  detailsModel: { width: 500, height: 400 },
  rangeModel: { min: 0, max: 100, value: 30 },
};
